### PR TITLE
tests: support libxml2 2.15

### LINKED ISSUE #187: Test failure with libxml 2.15.1
When running the test suite of this crate with libxml 2.15.1, I get:

```
failures:

---- serialization_as_html stdout ----

thread 'serialization_as_html' panicked at tests/base_tests.rs:282:3:
assertion `left == right` failed
  left: "<html><head><metahttp-equiv=\"Content-Type\"content=\"text/html;charset=UTF-8\"><title>PageTitle</title></head><body><h1>ThisisaHeading</h1><p>Thisisaparagraph.</p></body></html>"
 right: "<html><head><metacharset=\"UTF-8\"><title>PageTitle</title></head><body><h1>ThisisaHeading</h1><p>Thisisaparagraph.</p></body></html>"
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /usr/src/rustc-1.90.0/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.90.0/library/core/src/panicking.rs:75:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.90.0/library/core/src/panicking.rs:403:5
   4: base_tests::serialization_as_html
             at ./tests/base_tests.rs:282:3
   5: base_tests::serialization_as_html::{{closure}}
             at ./tests/base_tests.rs:261:27
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.90.0/library/core/src/ops/function.rs:253:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.90.0/library/core/src/ops/function.rs:253:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

It's not clear to me if it's a symptom for an actual issue or just a difference between versions that can be ignored.

Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1119024

### PR DESCRIPTION
**Pull request by wetneb**
Fixes #187.

### CODE REVIEW

File: tests/base_tests.rs [hunk 1]
```diff
@@ -279,5 +284,12 @@ fn serialization_as_html() {
 
   let doc_str = doc.to_string_with_options(options);
 
-  assert_eq!(strip_whitespace(&result_file), strip_whitespace(&doc_str));
+  let doc_without_whitespace = strip_whitespace(&doc_str);
+  if doc_without_whitespace != strip_whitespace(&result_file)
+    && doc_without_whitespace != strip_whitespace(&result_file_legacy)
+  {
+    panic!(
+      "Serialization as HTML of the source XML document is:\n\n{doc_str}\n\nExpected one of:\n\n{result_file}\n\nor\n\n{result_file_legacy}\n"
```
Comment (dginev) [inline tests/base_tests.rs]: You could have also done an `assert!( ... || ... )`  rather than a `panic!` I think.

Comment (wetneb) [reply tests/base_tests.rs]: True, not sure why I made it that convoluted…

**Comment by dginev** [comment]
Thank you for the speedy report and resolution, much appreciated!
